name: 🐛 Bug Report
description: Report a bug in this library.
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Describe the bug clearly.
      validations:
        required: true
  - type: input
    id: library-version
    attributes:
      label: Library Version
      placeholder: "e.g., 1.0.0"
      validations:
        required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      validations:
        required: true
  - type: textarea
    id: environment-info
    attributes:
      label: Environment Info
      description: Include relevant environment details (e.g., OS, React Native version).
      validations:
        required: true